services:
  - type: web
    name: faceit-insights
    runtime: node
    plan: free
    buildCommand: echo "no build"
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "10000"
      - key: FACEIT_API_KEY
        sync: false
